apiVersion: v1
kind: Pod
metadata:
  name: portfolio
  labels:
    app: portfolio
spec:
  containers:
  - name: portfolio
    image: athithyan402/hosted-docker-website:latest
    ports:
    - containerPort: 80